title: বাংলায় লিখি
author: শর্মা লুনা
email: 	sharmaojha2011@gmail.com
description: আমি বাংলায় মাতি উল্লাসে, করি বাংলায় হাহাকার, আমি সব দেখে শুনে ক্ষেপে গিয়ে করি বাংলায় চিৎকার
baseurl:
twitter_username:
github_username: 

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
